config/routes.rb
Rails.application.routes.draw do
  resources :incomes
  resources :portions
  resources :contract_historics
  resources :contracts
  devise_for :users, controllers: { sessions: "users/sessions"}
  root to: 'pages#home'

  get 'user/home', to: "pages/private_user#index"
  get 'user/contract/:id', to: "pages/private_user#contract"
  get 'user/income', to: "pages/private_user#income"
  get 'user/management', to: "pages/private_user#user_management"
  
  get 'user/income_new', to: "pages/private_user#income_new"
  #post 'user/income_create', to: "pages/private_user#income_create"
  
  get 'user/admin_new', to: "pages/private_user#admin_new"
  post 'user/admin_create', to: "pages/private_user#admin_create"
  
  get 'user/contract_new', to: "pages/private_user#contract_new"
  #post 'user/contract_create', to: "pages/private_user#contract_create"

  get 'user/list', to: "pages/private_user#list_user"
  
  get 'user/edit/:id', to: "pages/private_user#edit_user"

  #get 'user/extrato/:id', to: "pages/private_user#insert_extrato_user"
  
  get 'user/manager/:id', to: "pages/private_user#manager_portion_user"
end

app/controllers/pages/private_user_controller.rb
class Pages::PrivateUserController < ApplicationController

  def index
  end

  def contract
    @contract = current_user.contract.find_by(number:params[:id])
    if @contract.nil?
      redirect_to user_home_path
    end
  end

  def income
    @meses = ["JAN","FEV","MAR","ABR","MAI","JUN","JUL","AGO","SET","OUT","NOV","DEZ"]
  end

  def user_management
  end

  def income_new
    @income = Income.new
  end

  def income_create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to income_url(@income), notice: "Income was successfully created." }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  def contract_new
    @contract = Contract.new
  end

  def admin_new
    @admin = User.new
  end

  def admin_create
    @user = User.new(admin_params)
    respond_to do |format|
      if @user.save
        @admin = @user.build_user_role(role_id: Role.find_by(name:"Adm").id)
        if @admin.save
          format.html { redirect_to user_admin_new_path, notice: "admin was successfully created." }
          #format.json { render :show, status: :created, location: @income }
        end
      else
        format.html { redirect_to user_admin_new_path, notice: @user.errors}
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def list_user
    @select=0
  end

  def edit_user
    @user = ContractHistoric.find_by(id:params[:id]).contract.user
  end

  def admin_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def manager_portion_user
    @contract_historic = ContractHistoric.find_by(id:params[:id])
  end

  def insert_extrato_user
    @portion = ContractHistoric.find_by(id:params[:id]).portion
  end
end

app/views/pages/private_user/_header.html.erb
  <header class="site-header sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding: 0; font-family: Gadeg Bold Personal;">
      <!--link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"-->
        <div class="container-fluid" style="background: #202124">
          <a class="navbar-brand" href="#" style="padding-left: 5rem;">
            <%= image_tag("ED-LOGO-TRADER-OK.png", :alt => "", :width => "160", :class=> "d-inline-block align-text-top") %>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="box linha-vertical" style="border: 1px solid #ffffff24; height: 50px;"></div>

          <div class="collapse navbar-collapse" id="navbarText">
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
            <label class="btn btn-outline-success my-2 my-sm-0" style="border: none;">Bem Vindo <%= current_user.email %></label>
            </div>

    <!--button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
      <span class="navbar-toggler-icon"></span>
    </button-->
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Dark offcanvas</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <!--div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div-->
    </div>
            <div class="navbar-nav me-auto mb-2 mb-lg-0">
              <a href="/user/home" class="btn btn-outline-success my-2 my-sm-0" style="border-radius: 10px;">Home</a>
              <!--a href="#sobre" class="btn btn-outline-success my-2 my-sm-0" style="border-radius: 10px;">Contratos</a-->
              <a href="/user/income" class="btn btn-outline-success my-2 my-sm-0" style="border-radius: 10px;">Rendimentos</a>
              <li class="nav-item dropdown">
                <a class="dropdown-toggle btn btn-outline-success my-2 my-sm-0" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="border-radius: 10px; width: -webkit-fill-available;">
                  Contratos
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <% current_user.contract.each do |contract| %>
                    <li><a class="dropdown-item" href= <%= "/user/contract/#{contract.number}" %> ><%= contract.number%></a></li>
                  <% end %>
                </ul>
              </li>
            </div>

            <a href=<%= destroy_user_session_path %> data-method="delete" class="btn btn-outline-success" style="color: white; border: 2px solid green; border-radius: 90px;">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
              </svg>
              Sair
            </a >
          </div>
        </div>
    </nav>
  </header>

app/views/pages/private_user/_header2.html.erb
  <header class="site-header sticky-top">
    <nav class="navbar  navbar-dark bg-dark" style="padding: 0; font-family: Gadeg Bold Personal;">
      <!--link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"-->
        <div class="container-fluid" style="background: #202124">
       
          <a class="navbar-brand" href="/user/management" style="padding-left: 5rem;">
            <%= image_tag("ED-LOGO-TRADER-OK.png", :alt => "", :width => "160", :class=> "d-inline-block align-text-top") %>
          </a>
          
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
    
          <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel" style="background: rgb(33, 37, 41);">
      <div class="offcanvas-header" style="border-bottom: 10px solid white; margin-top: 0.89rem;">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Menu</h5>
        <hr>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/user/income_new">Inserir Rendimnento</a>
          </li>
          <hr>
          <li class="nav-item">
            <a class="nav-link" href="/user/admin_new">Adicionar Admin</a>
          </li>
          <hr>
          <li class="nav-item">
            <a class="nav-link" href="/user/contract_new">Criar Contrato</a>
          </li>
          <hr>
          <li class="nav-item">
            <a class="nav-link" href="/user/list">Editar Contrato</a>
          </li>
          <hr>
          <li class="nav-item">
            <a class="nav-link" href="#">Atualizar Dados Cadastrais</a>
          </li>
          <hr>
          <!--li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li-->
        </ul>
        
      </div>
    </div>
            

            <a href=<%= destroy_user_session_path %> data-method="delete" class="btn btn-outline-success" style="color: white; border: 2px solid green; border-radius: 90px;">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
              </svg>
              Sair
            </a >
          </div>
        </div>
    </nav>
  </header>

app/views/pages/private_user/admin_new.html.erb
<%= render 'pages/private_user/header2' %>
<p id="notice"><%= notice %></p>

<section class="signin">
  <div class="text-center">
  <h2 class="pb-2 border-bottom h3 mb-1 fw-normal" style="padding: 2rem">Cadastrar Admin</h2>
    <div calss="form-signin w-100 m-auto" style="max-width: 330px; padding: 15px; margin: auto; padding-top: 3rem;">

        <%= form_for @admin, url: user_admin_create_path, method: :post do |form| %>
        <%= render "devise/shared/error_messages", resource: @admin %> 
          <!--h1 class="h3 mb-3 fw-normal">sign in</h1-->

          <div class="form-floating">
            <%= form.email_field :email, class:"form-control", id:"floatingInput", placeholder:"name@example.com" %>
            <label for="floatingInput">Email</label>
          </div>
          <div class="form-floating">
            <%= form.password_field :password, class:"form-control", id:"floatingPassword", placeholder:"senha" %>
            <label for="floatingPassword">Senha</label>
          </div>
          <div class="form-floating" style="margin-bottom: 2rem;">
            <%= form.password_field :password_confirmation, class:"form-control", id:"floatingPassword", placeholder:"senha" %>
            <label for="floatingPassword">Confirmar Senha</label>
          </div>
          <button class=" w-100 btn-lg btn btn-outline-success my-2 my-sm-0" type="submit">Salvar</button>

        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/pages/private_user/contract.html.erb
<%= render 'pages/private_user/header' %>
<p id="notice"><%= notice %></p>

<section class="how-it-works-sec" id="faq" style="height: 100%">
  <div class="container px-4 py-5 sobre faq" id="featured-3">
    <h2 class="pb-2 border-bottom">Contratos</h2>
    <div class="accordion" id="accordionExample">
      <% @contract.contract_historic.all.order(open_date: :desc).each do |contract| %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading<%= contract.id %>" style="display: flex; align-items: center; flex-direction: row-reverse;">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= contract.id %>" aria-expanded="true" aria-controls="collapse<%= contract.id %>">
              Contrato <%= contract.open_date %>
            </button>
            <a href="<%= contract.contract.contract_doc.url %>" target="_blank" rel="noopener noreferrer" class="btn btn-outline-success" type="button" style="margin-right: 1%;"><i class="bi bi-download"></i></a>
          </h2>
          <div id="collapse<%= contract.id %>" class="accordion-collapse collapse" aria-labelledby="heading<%= contract.id %>" data-bs-parent="#accordionExample">
              <div class="accordion-item" style="max-height: 300px; overflow: auto;">
                <table class="table table-dark table-striped-columns">
                  <thead>
                    <tr>
                      <!--th scope="col">#</th-->
                      <th scope="col">Parcela</th>
                      <th scope="col">Valor</th>
                      <th scope="col">Status</th>
                      <th scope="col">Comprovante</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% contract.portion.all.each do |portion| %>
                      <tr>
                        <!--th scope="row">1</th-->
                        <td><%= portion.number%>ª</td>
                        <td>R$ <%= portion.value%></td>
                        <td><%= portion.status ? "Pago" : "-" %></td><!--Portion.find_by(id:4)[:proof].present?-->
                        <td><button <%= portion[:proof].present? ? "" : "disabled" %> type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#exampleModalScrollable"  onclick='textModal("Contrato - <%= contract.open_date %> | Parcela - <%= portion.number%>/<%= contract.portion.all.count %> ","<%= portion.proof.url %>")'><i class="bi bi-eye-fill"></i></button> | <button <%= portion[:proof].present? ? "" : "disabled" %> type="button" class="btn btn-outline-success"><i class="bi bi-download"></i></button> </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            <!--% end %-->
          </div>
        </div>
      <% end %>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalScrollable" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">

      <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">

          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalScrollableTitle">Contrato</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>

          <div class="modal-body">
            <div class="carousel-item active" style="display: flex; align-items: center; justify-content: center;">
              <%= image_tag("", id:"img_income", :alt => "", :class=> "d-inline-block align-text-top", 'aria-hidden' => "true", :preserveAspectRatio => "xMidYMid slice", :focusable => "false", :style => "height: -webkit-fill-available;") %>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>

<script>
  function textModal(title, text) {
    document.getElementById("exampleModalScrollableTitle").innerText=title;
    document.getElementById("img_income").src=text;
  }
</script>

app/views/pages/private_user/contract_new.html.erb
<%= render 'pages/private_user/header2' %>
<p id="notice"><%= notice %></p>

<section class="signin" style="margin-bottom: -5rem">
  <div class="text-center">
  <h2 class="pb-2 border-bottom h3 mb-1 fw-normal" style="padding: 2rem">Criar Contrato</h2>

    <div calss="form-signin w-100 m-auto" style="max-width: 330px; padding: 15px; margin: auto; padding-top: 3rem;">  


        <%= form_for @contract, method: :post do |form1| %>
          <%if params["user_id"].present?%>
            <%= hidden_field_tag "user_id", params["user_id"] %>
            <div class="form-floating">
              <input class="form-control" placeholder="name@example.com" type="text" name="value" value=<%=User.find_by(id:params["user_id"]).email%> disabled>
              <label for="floatingInput">Email</label>
            </div>
          <%else%> 
            <%= fields_for @user do |form| %>
              <div class="form-floating">
                <%= form.email_field :email, class:"form-control", id:"floatingInput", placeholder:"name@example.com" %>
                <label for="floatingInput">Email</label>
              </div>
              <div class="form-floating">
                <%= form.password_field :password, class:"form-control", id:"floatingPassword", placeholder:"senha" %>
                <label for="floatingPassword">Senha</label>
              </div>
            <% end %>
          <%end%>

          <%= fields_for @contract_historic do |form| %>
            <div class="form-floating">
              <%= form.text_field :value, class:"form-control", id:"floatingInput", placeholder:"name@example.com" %>
              <label for="floatingInput">Valor do Contrato</label>
            </div>
            <div class="form-floating">
              <%= form.text_field :num_portion, class:"form-control", id:"floatingPassword", placeholder:"senha" %>
              <label for="floatingPassword">Quantidade de Parcelas</label>
            </div>
            <div class="form-floating">
              <%= form.date_field :open_date, class:"form-control", id:"floatingPassword", placeholder:"data de abertura", style:"filter: contrast(0.0);"%>
              <label for="floatingPassword" style="opacity: 1;">Data de Abertura</label>
            </div>
          <% end %>

          <div class="form-floating">
            <%= form1.text_field :number, class:"form-control", id:"floatingPassword", placeholder:"senha" %>
            <label for="floatingPassword">Nº do Contrato</label>
          </div>
          <div class="form-floating" style="margin-bottom: 1rem; color: white;">
            <%= form1.file_field :contract_doc, class: "form-control", type: "file", accept: "application/pdf"  %>
            <small>Anexar o Contrato - Formato permitido:PDF</small>
          </div>

          <button class=" w-100 btn-lg btn btn-outline-success my-2 my-sm-0" type="submit">Salvar</button>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/pages/private_user/home_admin.html.erb
<%= render 'pages/private_user/header2' %>
<p id="notice"><%= notice %></p>

<section class="how-it-works-sec" id="index_user" style="height: 100%">
  <div class="container">

    <div class="text-center">  
      <div class="form-signin w-100 m-auto">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <%= image_tag("ED-LOGO-SOMBRA-TRADER.png", :alt => "", :width => "72", :height => "57", :class=> "mb-4") %>
          <h1 class="h3 mb-3 fw-normal">sign in</h1> 

          <div class="form-floating">
            <%= f.email_field :email, class:"form-control", id:"floatingInput", placeholder:"name@example.com" %>
            <label for="floatingInput">Email address</label>
          </div>
          <div class="form-floating">
            <%= f.password_field :password, class:"form-control", id:"floatingPassword", placeholder:"Password" %>
            <label for="floatingPassword">Password</label>
          </div>  
          <% if devise_mapping.rememberable? %>
            <div class="checkbox mb-3">
              <label>
                <%= f.check_box :remember_me %> Remember me
              </label>
            </div>
          <% end %>
          <button class=" w-100 btn-lg btn btn-outline-success my-2 my-sm-0" type="submit">Sign in</button>
          <!--p class="mt-5 mb-3 text-muted">&copy; 2017–2022</p-->
        <% end %>
      </div>
    </div>

  </div>
</section>



<%= form_with(model: portion) do |form| %>
  <% if portion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portion.errors.count, "error") %> prohibited this portion from being saved:</h2>

      <ul>
        <% portion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :proof %>
    <%= form.text_field :proof %>
  </div>

  <div class="field">
    <%= form.label :contract_historic_id %>
    <%= form.text_field :contract_historic_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/private_user/income.html.erb
<%= render 'pages/private_user/header' %>
<p id="notice"><%= notice %></p>

<section class="how-it-works-sec" id="faq" style="height: -webkit-fill-available; margin-bottom: -4rem;">
  <div class="container px-4 py-5 sobre faq" id="featured-3">
    <h2 class="pb-2 border-bottom">Rendimento Mensal da Empresa</h2>
    <div class="accordion" id="accordionExample" style="max-height: 500px; overflow-y: auto;">
      <table class="table table-hover table-dark" >

        <thead style="position: sticky !important; top: 0 !important; z-index: 1;">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Mês</th>
            <th scope="col">Ano</th>
            <th scope="col">Visualizar</th>
          </tr>
        </thead>
        <tbody>
          <% Income.all.order(reference_date: :desc).each_with_index do |income,index| %>
            <tr>
              <th scope="row"><%=index%></th>
              <td><%= @meses[income.reference_date.month - 1] %></td>
              <td><%= income.reference_date.year %></td>
              <td> <Button onclick='textModal("Rendimento <%= @meses[income.reference_date.month-1]%>/<%= income.reference_date.year %>","<%= income.income_doc.url %>")' type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#exampleModalScrollable"> <i class="bi bi-eye-fill"></i> </button> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalScrollable" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">

      <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">

          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalScrollableTitle">Rendimento <%= @meses[7-1] %>/2022</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>

          <div class="modal-body">
            <div class="carousel-item active" style="display: flex; align-items: center; justify-content: center;">
              <%= image_tag("", :alt => "", :class=> "d-inline-block align-text-top", 'aria-hidden' => "true", :preserveAspectRatio => "xMidYMid slice", :focusable => "false", :id => "img_income", :style => "height: -webkit-fill-available;") %>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>

<script>
  function textModal(title, text) {
    document.getElementById("exampleModalScrollableTitle").innerText=title;
    document.getElementById("img_income").src=text;
  }
</script>

app/views/pages/private_user/income_new.html.erb
<%= render 'pages/private_user/header2' %>
<p id="notice"><%= notice %></p>

<section class="how-it-works-sec" id="index_user" style="height: 100%">
  <div class="text-center">
    <div calss="container">
      <h2 class="pb-2 border-bottom h3 mb-1 fw-normal" style="padding: 2rem">Inserir Rendimento Mensal</h2>
      <div class="form-signin w-100 m-auto" style="display: flex; justify-content: center; padding-top: 3rem">

        <%= form_for @income do |form| %>

          <% if @income.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>
              <ul>
                <% @income.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-floating" style="display: flex; flex-direction: column-reverse;">
            <%= form.date_select :reference_date, class:"form-control", id:"floatingInput", placeholder:"name@example.com", style:"width: -webkit-fill-available; margin: 1rem;" %>
          </div>

          <div class="mb-3" style="width: -webkit-fill-available; margin: 1rem;">
            <!--input class="form-control" type="file" id="formFile"-->
            <%= form.file_field :income_doc, class: "form-control", type: "file", accept: "image/png, image/jpeg, image/jpg"%>
          </div>

          <div class="actions">
            <%= form.submit class:"btn btn-outline-success", style:"width: -webkit-fill-available; margin: 1rem;" ,value:"Salvar"%>
          </div>

        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/pages/private_user/index.html.erb
<%= render 'pages/private_user/header' %>
<p id="notice"><%= notice %></p>

<section class="how-it-works-sec" id="index_user" style="height: 100%">
  <div class="container">
    <h2 style="text-align: -webkit-center; padding: 2% 1% 1% 1%;">
      Seja Bem vindo(a) à EHTRADER
      <hr style="border: 1px solid #f9fafb">
      <p style="color: #f9fafb; font-size: medium; margin: -1%;">Aqui Cuidamos Bem dos Seus Ivestimentos</p>
    </h2>
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      </div>
      <div class="carousel-inner" style="height: -webkit-fill-available;">
        <div class="carousel-item active" style="display: flex; align-items: center; justify-content: center; height: 26rem;">
          <%= image_tag("#{Income.last.income_doc.url}", :alt => "", :class=> "d-inline-block align-text-top", 'aria-hidden' => "true", :preserveAspectRatio => "xMidYMid slice", :focusable => "false", :style => "height: -webkit-fill-available;") %>
        </div>
      </div>
    </div>
  </div>
</section>

<!--%= render 'portion' %-->