config/routes.rb
Rails.application.routes.draw do
  resources :incomes
  resources :portions
  resources :contract_historics
  resources :contracts
  devise_for :users, controllers: { sessions: "users/sessions"}
  root to: 'pages#home'

  get 'user/home', to: "pages/private_user#index"
  get 'user/contract/:id', to: "pages/private_user#contract"
  get 'user/income', to: "pages/private_user#income"
  get 'user/management', to: "pages/private_user#user_management"
  
  get 'user/income_new', to: "pages/private_user#income_new"
  #post 'user/income_create', to: "pages/private_user#income_create"
  
  get 'user/admin_new', to: "pages/private_user#admin_new"
  post 'user/admin_create', to: "pages/private_user#admin_create"
  
  get 'user/contract_new', to: "pages/private_user#contract_new"
  #post 'user/contract_create', to: "pages/private_user#contract_create"

  get 'user/list', to: "pages/private_user#list_user"
  
  get 'user/edit/:id', to: "pages/private_user#edit_user"

  #get 'user/extrato/:id', to: "pages/private_user#insert_extrato_user"
  
  get 'user/manager/:id', to: "pages/private_user#manager_portion_user"
end

app/models/income.rb
class Income < ApplicationRecord
  mount_uploader :income_doc, IncomeDocUploader
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: %i[ show edit update destroy ]

  # GET /incomes or /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1 or /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes or /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to user_income_new_path, notice: "Income was successfully created." }
        #format.json { render :new, status: :created, location: user_income_new_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1 or /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to income_url(@income), notice: "Income was successfully updated." }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1 or /incomes/1.json
  def destroy
    @income.destroy

    respond_to do |format|
      format.html { redirect_to incomes_url, notice: "Income was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def income_params
      params.require(:income).permit(:reference_date, :income_doc)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html copy.erb
<%= form_with(model: income) do |form| %>
  <% if income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% income.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reference_date %>
    <%= form.date_select :reference_date %>
  </div>

  <div class="field">
    <%= form.label :income_doc %>
    <%= form.text_field :income_doc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Incomes</h1>

<table>
  <thead>
    <tr>
      <th>Reference date</th>
      <th>Income doc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= income.reference_date %></td>
        <td><%= income.income_doc %></td>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reference date:</strong>
  <%= @income.reference_date %>
</p>

<p>
  <strong>Income doc:</strong>
  <%= @income.income_doc %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>