config/routes.rb
Rails.application.routes.draw do
  resources :incomes
  resources :portions
  resources :contract_historics
  resources :contracts
  devise_for :users, controllers: { sessions: "users/sessions"}
  root to: 'pages#home'

  get 'user/home', to: "pages/private_user#index"
  get 'user/contract/:id', to: "pages/private_user#contract"
  get 'user/income', to: "pages/private_user#income"
  get 'user/management', to: "pages/private_user#user_management"
  
  get 'user/income_new', to: "pages/private_user#income_new"
  #post 'user/income_create', to: "pages/private_user#income_create"
  
  get 'user/admin_new', to: "pages/private_user#admin_new"
  post 'user/admin_create', to: "pages/private_user#admin_create"
  
  get 'user/contract_new', to: "pages/private_user#contract_new"
  #post 'user/contract_create', to: "pages/private_user#contract_create"

  get 'user/list', to: "pages/private_user#list_user"
  
  get 'user/edit/:id', to: "pages/private_user#edit_user"

  #get 'user/extrato/:id', to: "pages/private_user#insert_extrato_user"
  
  get 'user/manager/:id', to: "pages/private_user#manager_portion_user"
end

app/models/contract_historic.rb
class ContractHistoric < ApplicationRecord
  belongs_to :contract
  has_many :portion, dependent: :destroy
end

app/controllers/contract_historics_controller.rb
class ContractHistoricsController < ApplicationController
  before_action :set_contract_historic, only: %i[ show edit update destroy ]

  # GET /contract_historics or /contract_historics.json
  def index
    @contract_historics = ContractHistoric.all
  end

  # GET /contract_historics/1 or /contract_historics/1.json
  def show
  end

  # GET /contract_historics/new
  def new
    @contract_historic = ContractHistoric.new
  end

  # GET /contract_historics/1/edit
  def edit
  end

  # POST /contract_historics or /contract_historics.json
  def create
    @contract_historic = ContractHistoric.new(contract_historic_params)

    respond_to do |format|
      if @contract_historic.save
        format.html { redirect_to contract_historic_url(@contract_historic), notice: "Contract historic was successfully created." }
        format.json { render :show, status: :created, location: @contract_historic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contract_historic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contract_historics/1 or /contract_historics/1.json
  def update
    respond_to do |format|
      if @contract_historic.update(contract_historic_params)
        format.html { redirect_to contract_historic_url(@contract_historic), notice: "Contract historic was successfully updated." }
        format.json { render :show, status: :ok, location: @contract_historic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contract_historic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contract_historics/1 or /contract_historics/1.json
  def destroy
    @contract_historic.destroy

    respond_to do |format|
      format.html { redirect_to contract_historics_url, notice: "Contract historic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract_historic
      @contract_historic = ContractHistoric.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contract_historic_params
      params.require(:contract_historic).permit(:value, :num_portion, :status, :open_date, :contract_id)
    end
end

app/helpers/contract_historics_helper.rb
module ContractHistoricsHelper
end

app/views/contract_historics/_form.html.erb
<%= form_with(model: contract_historic) do |form| %>
  <% if contract_historic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contract_historic.errors.count, "error") %> prohibited this contract_historic from being saved:</h2>

      <ul>
        <% contract_historic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :num_portion %>
    <%= form.text_field :num_portion %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :open_date %>
    <%= form.text_field :open_date %>
  </div>

  <div class="field">
    <%= form.label :contract_id %>
    <%= form.text_field :contract_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contract_historics/edit.html.erb
<h1>Editing Contract Historic</h1>

<%= render 'form', contract_historic: @contract_historic %>

<%= link_to 'Show', @contract_historic %> |
<%= link_to 'Back', contract_historics_path %>

app/views/contract_historics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contract Historics</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Num portion</th>
      <th>Status</th>
      <th>Open date</th>
      <th>Contract</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contract_historics.each do |contract_historic| %>
      <tr>
        <td><%= contract_historic.value %></td>
        <td><%= contract_historic.num_portion %></td>
        <td><%= contract_historic.status %></td>
        <td><%= contract_historic.open_date %></td>
        <td><%= contract_historic.contract_id %></td>
        <td><%= link_to 'Show', contract_historic %></td>
        <td><%= link_to 'Edit', edit_contract_historic_path(contract_historic) %></td>
        <td><%= link_to 'Destroy', contract_historic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract Historic', new_contract_historic_path %>

app/views/contract_historics/new.html.erb
<h1>New Contract Historic</h1>

<%= render 'form', contract_historic: @contract_historic %>

<%= link_to 'Back', contract_historics_path %>

app/views/contract_historics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @contract_historic.value %>
</p>

<p>
  <strong>Num portion:</strong>
  <%= @contract_historic.num_portion %>
</p>

<p>
  <strong>Status:</strong>
  <%= @contract_historic.status %>
</p>

<p>
  <strong>Open date:</strong>
  <%= @contract_historic.open_date %>
</p>

<p>
  <strong>Contract:</strong>
  <%= @contract_historic.contract_id %>
</p>

<%= link_to 'Edit', edit_contract_historic_path(@contract_historic) %> |
<%= link_to 'Back', contract_historics_path %>