config/routes.rb
Rails.application.routes.draw do
  resources :incomes
  resources :portions
  resources :contract_historics
  resources :contracts
  devise_for :users, controllers: { sessions: "users/sessions"}
  root to: 'pages#home'

  get 'user/home', to: "pages/private_user#index"
  get 'user/contract/:id', to: "pages/private_user#contract"
  get 'user/income', to: "pages/private_user#income"
  get 'user/management', to: "pages/private_user#user_management"
  
  get 'user/income_new', to: "pages/private_user#income_new"
  #post 'user/income_create', to: "pages/private_user#income_create"
  
  get 'user/admin_new', to: "pages/private_user#admin_new"
  post 'user/admin_create', to: "pages/private_user#admin_create"
  
  get 'user/contract_new', to: "pages/private_user#contract_new"
  #post 'user/contract_create', to: "pages/private_user#contract_create"

  get 'user/list', to: "pages/private_user#list_user"
  
  get 'user/edit/:id', to: "pages/private_user#edit_user"

  #get 'user/extrato/:id', to: "pages/private_user#insert_extrato_user"
  
  get 'user/manager/:id', to: "pages/private_user#manager_portion_user"
end

app/models/portion.rb
class Portion < ApplicationRecord
  belongs_to :contract_historic
  mount_uploader :proof, ProofUploader
end

app/controllers/portions_controller.rb
class PortionsController < ApplicationController
  before_action :set_portion, only: %i[ show edit update destroy ]

  # GET /portions or /portions.json
  def index
    @portions = Portion.all
  end

  # GET /portions/1 or /portions/1.json
  def show
  end

  # GET /portions/new
  def new
    @portion = Portion.new
  end

  # GET /portions/1/edit
  def edit
  end

  # POST /portions or /portions.json
  def create
    @portion = Portion.new(portion_params)

    respond_to do |format|
      if @portion.save
        format.html { redirect_to portion_url(@portion), notice: "Portion was successfully created." }
        format.json { render :show, status: :created, location: @portion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @portion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portions/1 or /portions/1.json
  def update
    respond_to do |format|
      if @portion.update(proof:params[:portion][:proof] , status:true)
        format.html { redirect_to "/user/manager/#{@portion.contract_historic_id}", notice: "Portion was successfully updated." }
        #format.json { render :show, status: :ok, location: @portion }
      else
        format.html { redirect_to "/user/manager/#{@portion.contract_historic_id}", notice: "Not successfully updated."}
        #format.json { render json: @portion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portions/1 or /portions/1.json
  def destroy
    @portion.destroy

    respond_to do |format|
      format.html { redirect_to portions_url, notice: "Portion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portion
      @portion = Portion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def portion_params
      params.require(:portion).permit(:number, :value, :status, :proof, :contract_historic_id)
    end
end

app/helpers/portions_helper.rb
module PortionsHelper
end

app/views/portions/_form.html.erb
<%= form_with(model: portion) do |form| %>
  <% if portion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portion.errors.count, "error") %> prohibited this portion from being saved:</h2>

      <ul>
        <% portion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :proof %>
    <%= form.text_field :proof %>
  </div>

  <div class="field">
    <%= form.label :contract_historic_id %>
    <%= form.text_field :contract_historic_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portions/edit.html.erb
<h1>Editing Portion</h1>

<%= render 'form', portion: @portion %>

<%= link_to 'Show', @portion %> |
<%= link_to 'Back', portions_path %>

app/views/portions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portions</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Value</th>
      <th>Status</th>
      <th>Proof</th>
      <th>Contract historic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portions.each do |portion| %>
      <tr>
        <td><%= portion.number %></td>
        <td><%= portion.value %></td>
        <td><%= portion.status %></td>
        <td><%= portion.proof %></td>
        <td><%= portion.contract_historic_id %></td>
        <td><%= link_to 'Show', portion %></td>
        <td><%= link_to 'Edit', edit_portion_path(portion) %></td>
        <td><%= link_to 'Destroy', portion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portion', new_portion_path %>

app/views/portions/new.html.erb
<h1>New Portion</h1>

<%= render 'form', portion: @portion %>

<%= link_to 'Back', portions_path %>

app/views/portions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @portion.number %>
</p>

<p>
  <strong>Value:</strong>
  <%= @portion.value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @portion.status %>
</p>

<p>
  <strong>Proof:</strong>
  <%= @portion.proof %>
</p>

<p>
  <strong>Contract historic:</strong>
  <%= @portion.contract_historic_id %>
</p>

<%= link_to 'Edit', edit_portion_path(@portion) %> |
<%= link_to 'Back', portions_path %>